[package]
name = "fsa"
version = "0.1.0"
authors = ["Nick Vathis <nvathis@gmail.com>"]
build = "build_lalrpop.rs"
edition = "2018"

[dependencies]
lalrpop-util = "0.16.2"
regex = "1.1.0"
lazy_static = "1.2.0"

[build-dependencies]
lalrpop = "0.16.2"
