[package]
name = "fsa"
version = "0.1.0"
authors = ["Nick Vathis <nvathis@gmail.com>"]
build = "build_lalrpop.rs"

[build-dependencies]
lalrpop = "~0.15"

[dependencies]
lalrpop-util = "~0.15"
regex = "~0.2"
lazy_static = "~1.0.0"
